### ISSUE TITLE
Add LGPL2.1 licence

### ISSUE THREAD

**Issue by luzpaz** [conda-forge/freecad-feedstock#12]
On https://anaconda.org/freecad/freecad/badges it shows:
![license](https://anaconda.org/freecad/freecad/badges/license.svg)

Can we add LGPL2.1 ?

**Comment by kmuehlbauer** [comment]
@luzpaz You would need to raise this at anaconda default channel. Conda-forge is OK: https://anaconda.org/conda-forge/freecad/badges

**Comment by luzpaz** [comment]
Why does the summary of https://anaconda.org/conda-forge/freecad/badges
say: `Simple, fast, extensible JSON encoder/decoder for Python` ?

**Comment by kmuehlbauer** [comment]
Because the comitter of the recipe did not change this line, which is from the recipe template.

**Comment by kmuehlbauer** [comment]
@luzpaz I have to take that back. The recipe here is OK, but somehow the summary line wasn't updated at https://anaconda.org/conda-forge/freecad.

ping @looooo ping @conda-forge/core

**Comment by looooo** [comment]
ref: https://github.com/Anaconda-Platform/anaconda-client/issues/477

Hopefully this will be solved soon. But there is nothing I can do about it.

**Comment by looooo** [comment]
It looks like both issues (license and summary) is solved for the conda-forge package. The freecad-channel has no summary and no license.

**Comment by looooo** [comment]
- [ ] TODO: set license to LGPL2.1 in next iteration

**Comment by looooo** [comment]
I think this should be fixed now. Description looks fine now.

**Comment by looooo** [comment]
At least for conda-forge channel. There are still issues with the freecad channel

**Comment by luzpaz** [comment]
Yea, shows LGPL2.0 and we want 2.1
