### ISSUE TITLE
freecad not importable

### ISSUE THREAD

**Issue by basnijholt** [conda-forge/freecad-feedstock#21]
I've installed FreeCAD via conda:
```
In [1]: import freecad
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-994cf2df5aec> in <module>
----> 1 import FreeCAD

ModuleNotFoundError: No module named 'FreeCAD'
```

It works when doing 
```
import os, sys
sys.path.append(`os.path.join(os.environ["CONDA_PREFIX"], "lib")
```

However, I don't think this should be necessary.

What works is to do:
```
$ find miniconda3/pkgs/ -maxdepth 1 -type d -name "freecad*"
miniconda3/pkgs/freecad-0.18b0-py36h275e31e_2
miniconda3/pkgs/freecad-0.18.1-py37h648b96a_1
```
Then add 
```
echo "$HOME/miniconda3/pkgs/freecad-0.18.1-py37h648b96a_1/lib" > miniconda3/envs/py36/lib/python3.6/site-packages/freecad.pth
```

I think it should be possible to do this automatically, I just don't know how.

**Comment by looooo** [comment]
FreeCAD is a bit difficult in this regard. The problem here is that there is an option to install different FreeCAD versions in the same environment.
For conda I think we don't want this option an therefor your suggestion should be save to be added to the build-script. I will try this on the weekly builds provided here:
https://anaconda.org/freecad/freecad/files?version=0.19.pre

**Comment by looooo** [comment]
Btw.: If there will be a way to import FreeCAD directly from python it will be accessable with:
`import freecad.app`

`freecad` itself is reserved as a namespace-package (I guess this is how it is called) and already used for 3rd-party modules.

**Comment by bollwyvl** [comment]
Over on cadquery, they had a [relatively complicated](https://github.com/dcowden/cadquery/blob/master/cadquery/freecad_impl/__init__.py) but serviceable way to deal with the most plausible install locations. 

At the end of it, for the conda-forge case, you'd basically:
```python
import sys
import os
sys.path.insert(os.path.join(sys.prefix, "lib")) # or Library on windows
import FreeCAD
```
Not ideal, by any means, but does appear to still work!

**Comment by looooo** [comment]
I am working on a better solution:
https://github.com/conda-forge/staged-recipes/pull/10082
https://github.com/looooo/freecad.python

this will add the possibilty to import freecad directly:

```
from freecad import app   # same as import FreeCAD as app
from freecad import part   # and so on
```

**Comment by looooo** [comment]
with the meta-package `freecad.python` it's now possible to import freecad directly, which will do the modification of sys.path automatically.

```
from freecad import app # does the path modification
import Part
```

**Comment by basnijholt** [comment]
@looooo, thanks a lot for fixing the issue!

I see that https://github.com/conda-forge/freecad.python-feedstock is archived, why is that?

**Comment by looooo** [comment]
It's now included in freecad source and will be enabled by default for the next release.

**Comment by basnijholt** [comment]
What will the import syntax be?

And is this documented anywhere?

**Comment by looooo** [comment]
This is work in progress. For now, it's best to use this syntax:
```
import freecad
import Part as part
import Draft as draft
```
This should work either by using 0.19pre or by using 0.18 + freecad.python. This doesn't work with packages other than conda, but I hope with 0.19 release also other debian/redhat maintainers will support this.

In the future, this will be changed to the syntax mentioned [here](https://github.com/conda-forge/freecad-feedstock/issues/21#issuecomment-551013581) But this is not yet possible. To get to this point first the community need to agree on the proposal:
https://github.com/looooo/FreeCAD-Enhancement-Proposals/blob/FEP01/FEP01.md
