### ISSUE TITLE
remove some builds with wrong description

### ISSUE THREAD

**Issue by looooo** [conda-forge/freecad-feedstock#7]
There were added some packages with a wrong package-information: https://github.com/conda-forge/freecad-feedstock/pull/4

I updated this information but anaconda.org still shows the wrong information:
![bildschirmfoto von 2018-06-26 10-50-27](https://user-images.githubusercontent.com/5084704/41900341-ccb74c70-792e-11e8-935a-9a032e61c4df.png)

Maybe someone from @conda-forge/core finds some time to remove the following packages:

![bildschirmfoto von 2018-06-26 10-49-47](https://user-images.githubusercontent.com/5084704/41900298-b32b2790-792e-11e8-9306-2ac555c19d9c.png)

This hopefully resolves this issue.

**Comment by mbargull** [comment]
xref: https://github.com/Anaconda-Platform/anaconda-client/issues/477

**Comment by dougalsutherland** [comment]
I marked those two `broken`, but it didn't seem to fix the description. So I deleted them (since they were only around for a day and had very few downloads to break anyone's reproducibility); that didn't seem to help either.

**Comment by looooo** [comment]
I think this hast Bern resolved
